package com.cwsni.world.model.engine.modifiers;

public enum CountryModifier {
	
	POWER_FOCUS,
	ARMY_EFFECTIVENESS,
	GOVERNMENT_INFLUENCE_DISTANCE,
	PROVINCE_GOVERNMENT_INFLUENCE,
	PROVINCE_LOYALTY,
	PROVINCE_TAX_EFFECTIVENESS
}
