package com.cwsni.world.client.desktop.game.map;

public enum MapMode {
	GEO,
	POLITICAL,
	STATES,
	POPULATION,
	POPULATION_2,
	LOYALTY,
	LOYALTY_DANGEROUS,
	GOVERNMENT_INFLUENCE,
	WEALTH,
	INFRASTRUCTURE,
	CULTURE,
	SOIL,
	SOIL_2,
	SCIENCE_AGRICULTURE,
	SCIENCE_MEDICINE,
	SCIENCE_ADMINISTRATION,
	DISEASE
}
