package com.cwsni.world.client.desktop.game.map;

public enum MapModeEnum {
	EVENT,
	GEO,
	POLITICAL,
	DIPLOMACY,
	REACHABLE_LANDS,
	STATES,
	POPULATION,
	LOYALTY,
	LOYALTY_DANGEROUS,
	GOVERNMENT_INFLUENCE,
	WEALTH,
	INFRASTRUCTURE,
	CULTURE,
	SOIL_FERTILITY,
	SOIL_RAW_FERTILITY,
	SCIENCE_AGRICULTURE,
	SCIENCE_MEDICINE,
	SCIENCE_ADMINISTRATION,
}
